name: "Set Label"
on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.1
        with:
          title-or-body: "body"
          parameters: '[ {"keywords": ["/lgtm", "/approve"], "labels": ["lgtm"], "assignees": ["chilly-bot"]}]'
          github-token: "${{ secrets.CHILLY_BOT_TOKEN }}"
